### PR TITLE
Fix for #13

### PR DESCRIPTION
**Pull request by zaroxh**
Allow overriding the default KCEF AppHandler

### CODE REVIEW

**Comment by DatL4g** [comment]
@zaroxh Was something not working?, Were just going to review it

**Comment by zaroxh** [comment]
I accidentally didn't sign the commit, then I wanted to sign it afterwards but used the wrong email. I wanted to re-open merge request when I fixed the signing issues. But you can also just look at the changes and commit them, it is not much.

**Comment by DatL4g** [comment]
Thats great! I already wanted to point out the signing as it's a requirement for the repository and a bit tricky to disable it just to merge PRs.

So please create a new PR with the signed commit 👍🏻

**Comment by zaroxh** [comment]
Okay, will do.

**Pull request closed without merging**
